title: Fabric w/ Azure Databricks
description: This lab walks you through setting up the development environment, deploying your appication, and implementing load testing and secure practices.
theme: just-the-docs

aux_links:
  "TechBoost Fabric wth Databricks for Data Analytics": 
    - "https://github.com/microsoft/TechBoost-Fabric-with-Databricks-for-Data-Analytics"

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note 
    color: purple
  warning:
    title: Warning
    color: red
