title: Implementing DevOps practices
description: This lab walks you through setting up the development environment, deploying your appication, and implementing load testing and secure practices.
theme: just-the-docs

# url: https://v-stephclark.github.io/TechExcel-Implementing-DevOps-practices-to-accelerate-developer-productivity-coaches/

aux_links:
  "TechExcel: Implementing DevOps practices to accelerate developer productivity": 
    - "https://github.com/microsoft/TechExcel-Implementing-DevOps-practices-to-accelerate-developer-productivity"
exclude:
  - Solution/
callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note 
    color: purple
  warning:
    title: Warning
    color: red
